let jobListings = [
    {
    	isFeatured: true,
    	jobTitle: 'Senior Frontend Developer',
        jobSummary: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rerum vero alias voluptate saepe optio voluptates labore dignissimos aliquam sapiente enim voluptatem omnis, vel inventore eveniet ab nisi eius commodi non.',
    	dateCreated: (new Date().getTime()) - (86400000 * 1),
    	typeOfEmployment: 'Full Time',
    	location: 'USA only',
    	role: 'Frontend',
    	level: 'Senior',
        lengthOfExp: '15+ Years',
    	languages: ['HTML', 'CSS', 'JavaScript'],
    	tools: [],
        salary: 500000
    },
    {
    	isFeatured: true,
    	jobTitle: 'Fullstack Developer',
        jobSummary: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rerum vero alias voluptate saepe optio voluptates labore dignissimos aliquam sapiente enim voluptatem omnis, vel inventore eveniet ab nisi eius commodi non.',
    	dateCreated: (new Date().getTime()) - (86400000 * 1),
    	typeOfEmployment: 'Part Time',
    	location: 'Remote',
    	role: 'Fullstack',
    	level: 'Midweight',
        lengthOfExp: '6+ Years',
    	languages: ['Python'],
    	tools: ['React'],
        salary: 300000
    },
    {
    	isFeatured: false,
    	jobTitle: 'Junior Frontend Developer',
        jobSummary: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rerum vero alias voluptate saepe optio voluptates labore dignissimos aliquam sapiente enim voluptatem omnis, vel inventore eveniet ab nisi eius commodi non.',
    	dateCreated: (new Date().getTime()) - (86400000 * 2),
    	typeOfEmployment: 'Part Time',
    	location: 'USA only',
    	role: 'Frontend',
    	level: 'Junior',
        lengthOfExp: '1-2 Years',
    	languages: ['JavaScript'],
    	tools: ['React', 'Sass'],
        salary: 250000
    },
    {
    	isFeatured: false,
    	jobTitle: 'Junior Frontend Developer',
        jobSummary: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rerum vero alias voluptate saepe optio voluptates labore dignissimos aliquam sapiente enim voluptatem omnis, vel inventore eveniet ab nisi eius commodi non.',
    	dateCreated: (new Date().getTime()) - (86400000 * 5),
    	typeOfEmployment: 'Contract',
    	location: 'USA only',
    	role: 'Frontend',
    	level: 'Junior',
        lengthOfExp: '6 Months',
    	languages: ['CSS', 'JavaScript'],
    	tools: [],
        salary: 50000
    },
    {
    	isFeatured: false,
    	jobTitle: 'Software Engineer',
        jobSummary: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rerum vero alias voluptate saepe optio voluptates labore dignissimos aliquam sapiente enim voluptatem omnis, vel inventore eveniet ab nisi eius commodi non.',
    	dateCreated: (new Date().getTime()) - (86400000 * 7),
    	typeOfEmployment: 'Full Time',
    	location: 'USA only',
    	role: 'Fullstack',
    	level: 'Midweight',
        lengthOfExp: '6-7 Years',
    	languages: ['JavaScript', 'Ruby'],
    	tools: ['Sass'],
        salary: 250000
    },
    {
    	isFeatured: false,
    	jobTitle: 'Junior Backend Developer',
        jobSummary: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rerum vero alias voluptate saepe optio voluptates labore dignissimos aliquam sapiente enim voluptatem omnis, vel inventore eveniet ab nisi eius commodi non.',
    	dateCreated: (new Date().getTime()) - (86400000 * 14),
    	typeOfEmployment: 'Full Time',
    	location: 'UK only',
    	role: 'Backend',
    	level: 'Junior',
        lengthOfExp: '6 Months',
    	languages: ['Ruby'],
    	tools: ['RoR'],
        salary: 75000
    },
    {
    	isFeatured: false,
    	jobTitle: 'Junior Developer',
        jobSummary: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rerum vero alias voluptate saepe optio voluptates labore dignissimos aliquam sapiente enim voluptatem omnis, vel inventore eveniet ab nisi eius commodi non.',
    	dateCreated: (new Date().getTime()) - (86400000 * 14),
    	typeOfEmployment: 'Full Time',
    	location: 'Worldwide',
    	role: 'Frontend',
    	level: 'Junior',
        lengthOfExp: '1-2 Years',
    	languages: ['HTML', 'JavaScript'],
    	tools: ['Sass'],
        salary: 80000
    },
    {
    	isFeatured: false,
    	jobTitle: 'Junior Frontend Developer',
        jobSummary: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rerum vero alias voluptate saepe optio voluptates labore dignissimos aliquam sapiente enim voluptatem omnis, vel inventore eveniet ab nisi eius commodi non.',
    	dateCreated: (new Date().getTime()) - (86400000 * 14),
    	typeOfEmployment: 'Full Time',
    	location: 'USA only',
    	role: 'Frontend',
    	level: 'Junior',
        lengthOfExp: '3 years',
    	languages: ['JavaScript'],
    	tools: ['Vue', 'Sass'],
        salary: 65000
    },
    {
    	isFeatured: false,
    	jobTitle: 'Full Stack Engineer',
        jobSummary: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rerum vero alias voluptate saepe optio voluptates labore dignissimos aliquam sapiente enim voluptatem omnis, vel inventore eveniet ab nisi eius commodi non.',
    	dateCreated: (new Date().getTime()) - (86400000 * 21),
    	typeOfEmployment: 'Full Time',
    	location: 'Worldwide',
    	role: 'Fullstack',
    	level: 'Midweight',
        lengthOfExp: '8 years',
    	languages: ['JavaScript', 'Python'],
    	tools: ['Django'],
        salary: 185000
    },
    {
    	isFeatured: false,
    	jobTitle: 'Front-end Dev',
        jobSummary: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rerum vero alias voluptate saepe optio voluptates labore dignissimos aliquam sapiente enim voluptatem omnis, vel inventore eveniet ab nisi eius commodi non.',
    	dateCreated: (new Date().getTime()) - (86400000 * 30),
    	typeOfEmployment: 'Part Time',
    	location: 'Worldwide',
    	role: 'Frontend',
    	level: 'Junior',
        lengthOfExp: '9 Months',
    	languages: ['JavaScript'],
    	tools: ['React', 'Sass'],
        salary: 67000
    },
    {
        isFeatured: true,
        jobTitle: 'Senior Frontend Developer',
        jobSummary: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rerum vero alias voluptate saepe optio voluptates labore dignissimos aliquam sapiente enim voluptatem omnis, vel inventore eveniet ab nisi eius commodi non.',
        dateCreated: (new Date().getTime()) - (86400000 * 12),
        typeOfEmployment: 'Full Time',
        location: 'USA only',
        role: 'Frontend',
        level: 'Senior',
        lengthOfExp: '15+ Years',
        languages: ['HTML', 'CSS', 'JavaScript'],
        tools: [],
        salary: 500000
    },
    {
        isFeatured: true,
        jobTitle: 'Fullstack Developer',
        jobSummary: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rerum vero alias voluptate saepe optio voluptates labore dignissimos aliquam sapiente enim voluptatem omnis, vel inventore eveniet ab nisi eius commodi non.',
        dateCreated: (new Date().getTime()) - (86400000 * 21),
        typeOfEmployment: 'Part Time',
        location: 'Remote',
        role: 'Fullstack',
        level: 'Midweight',
        lengthOfExp: '6+ Years',
        languages: ['Python'],
        tools: ['React'],
        salary: 300000
    },
    {
        isFeatured: false,
        jobTitle: 'Junior Frontend Developer',
        jobSummary: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rerum vero alias voluptate saepe optio voluptates labore dignissimos aliquam sapiente enim voluptatem omnis, vel inventore eveniet ab nisi eius commodi non.',
        dateCreated: (new Date().getTime()) - (86400000 * 42),
        typeOfEmployment: 'Part Time',
        location: 'USA only',
        role: 'Frontend',
        level: 'Junior',
        lengthOfExp: '1-2 Years',
        languages: ['JavaScript'],
        tools: ['React', 'Sass'],
        salary: 250000
    },
    {
        isFeatured: false,
        jobTitle: 'Junior Frontend Developer',
        jobSummary: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rerum vero alias voluptate saepe optio voluptates labore dignissimos aliquam sapiente enim voluptatem omnis, vel inventore eveniet ab nisi eius commodi non.',
        dateCreated: (new Date().getTime()) - (86400000 * 25),
        typeOfEmployment: 'Contract',
        location: 'USA only',
        role: 'Frontend',
        level: 'Junior',
        lengthOfExp: '6 Months',
        languages: ['CSS', 'JavaScript'],
        tools: [],
        salary: 50000
    },
    {
        isFeatured: false,
        jobTitle: 'Software Engineer',
        jobSummary: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rerum vero alias voluptate saepe optio voluptates labore dignissimos aliquam sapiente enim voluptatem omnis, vel inventore eveniet ab nisi eius commodi non.',
        dateCreated: (new Date().getTime()) - (86400000 * 57),
        typeOfEmployment: 'Full Time',
        location: 'USA only',
        role: 'Fullstack',
        level: 'Midweight',
        lengthOfExp: '6-7 Years',
        languages: ['JavaScript', 'Ruby'],
        tools: ['Sass'],
        salary: 250000
    },
    {
        isFeatured: false,
        jobTitle: 'Junior Backend Developer',
        jobSummary: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rerum vero alias voluptate saepe optio voluptates labore dignissimos aliquam sapiente enim voluptatem omnis, vel inventore eveniet ab nisi eius commodi non.',
        dateCreated: (new Date().getTime()) - (86400000 * 114),
        typeOfEmployment: 'Full Time',
        location: 'UK only',
        role: 'Backend',
        level: 'Junior',
        lengthOfExp: '6 Months',
        languages: ['Ruby'],
        tools: ['RoR'],
        salary: 75000
    },
    {
        isFeatured: false,
        jobTitle: 'Junior Developer',
        jobSummary: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rerum vero alias voluptate saepe optio voluptates labore dignissimos aliquam sapiente enim voluptatem omnis, vel inventore eveniet ab nisi eius commodi non.',
        dateCreated: (new Date().getTime()) - (86400000 * 314),
        typeOfEmployment: 'Full Time',
        location: 'Worldwide',
        role: 'Frontend',
        level: 'Junior',
        lengthOfExp: '1-2 Years',
        languages: ['HTML', 'JavaScript'],
        tools: ['Sass'],
        salary: 80000
    },
    {
        isFeatured: false,
        jobTitle: 'Junior Frontend Developer',
        jobSummary: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rerum vero alias voluptate saepe optio voluptates labore dignissimos aliquam sapiente enim voluptatem omnis, vel inventore eveniet ab nisi eius commodi non.',
        dateCreated: (new Date().getTime()) - (86400000 * 14),
        typeOfEmployment: 'Full Time',
        location: 'USA only',
        role: 'Frontend',
        level: 'Junior',
        lengthOfExp: '3 years',
        languages: ['JavaScript'],
        tools: ['Vue', 'Sass'],
        salary: 65000
    },
    {
        isFeatured: false,
        jobTitle: 'Full Stack Engineer',
        jobSummary: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rerum vero alias voluptate saepe optio voluptates labore dignissimos aliquam sapiente enim voluptatem omnis, vel inventore eveniet ab nisi eius commodi non.',
        dateCreated: (new Date().getTime()) - (86400000 * 21),
        typeOfEmployment: 'Full Time',
        location: 'Worldwide',
        role: 'Fullstack',
        level: 'Midweight',
        lengthOfExp: '8 years',
        languages: ['JavaScript', 'Python'],
        tools: ['Django'],
        salary: 185000
    },
    {
        isFeatured: false,
        jobTitle: 'Front-end Dev',
        jobSummary: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rerum vero alias voluptate saepe optio voluptates labore dignissimos aliquam sapiente enim voluptatem omnis, vel inventore eveniet ab nisi eius commodi non.',
        dateCreated: (new Date().getTime()) - (86400000 * 30),
        typeOfEmployment: 'Part Time',
        location: 'Worldwide',
        role: 'Frontend',
        level: 'Junior',
        lengthOfExp: '9 Months',
        languages: ['JavaScript'],
        tools: ['React', 'Sass'],
        salary: 67000
    }
];

for(let i = 0; i < jobListings.length; i++){
    jobListings[i].fakeId = i + 1;
    jobListings[i].companyFakeId = Math.floor(Math.random() * (10 - 0) + 1 );
}

module.exports = jobListings;